name: Three Lefts Gaming
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37422
title: Three Lefts Interplanetary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000102'
    - '#012c5e'
    - '#fffffb'
    - '#0a97cd'
    - '#a9e0f3'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
